### ISSUE TITLE
【企画参加登録】企画参加登録フォームを同時に複数作成できるようにする

### ISSUE THREAD

**Issue by SofPyon** [portaldots/PortalDots#584]
## 背景

例えば、１年のうちに「A祭」と「B祭」の２つの学園祭が開催される場合でも、１回のユーザー登録だけで両方の学園祭の参加登録ができたら嬉しい。

## 実装内容

- 企画参加登録フォームを複数作成できるようにする
    - 参加登録フォームごとに、異なるカスタムフォームや必要人数を設定できる。
- circles テーブルに、新しく `event_id` というカラムを追加
- どの企画参加登録フォームから登録されたのかを区別しやすいよう、それぞれの企画には自動的にタグが設定される。
- ~~お知らせ、配布資料、申請、スケジュールなども、全て `event_id` と紐付ける~~
    - ~~各イベントごとに、異なるお知らせ、配布資料、申請、スケジュールを表示~~
    - 大変そうなので実装しない
- ~~スタッフモードも、イベントごとに別のページに分けたい~~

## しないこと
- 全く関連のない複数のイベントを1つのPortalDotsインスタンスで管理できる機能。
    - イベントごとにお知らせなどを出し分けるのは大変なので実装しない。

**Comment by SofPyon** [comment]
## DB
###  参加種別 participation_types （旧 custom_forms テーブル）
ex. 食品販売

* id
* name
* description
* members_count_min
* members_count_max
    * この値が1の場合、企画参加登録フォームにある「メンバーを招待」画面はスキップされるようにしたい。
* form_id
* tag_id
    * この参加種別で登録した企画に付与されるタグのID（省略可）
    * ~~ここで指定されたタグは削除したり、後から他のタグに変更したり、企画からそのタグを削除できないようにする？~~

### 企画 circles

* id
* ...
* participation_type_id

## TODO
* [x] 参加種別を作成・編集・削除できる機能
* [x] 参加種別ごとにフォームを編集できる
* [x] 企画一覧画面は、参加種別ごとに異なる一覧を表示する。
* [x] circles→participation_types→forms→answers （getCustomFormAnswerメソッドの修正）
* [x] CustomFormモデル→ParticipationType
* [x] ParticipationTypeモデルにformへのリレーション
* [x] scopeWithoutCustomForms → scopeWithoutParticipationForms（スコープ名変更の一括置換、スコープの条件変更）←手軽
* [x] FormモデルのcustomFormリレーション→participationTypeリレーションに変更した上で一括置換 ←手軽
* [x] Permission.phpの権限名を修正
* [x] CirclesExportでCustomFormをロードする処理
* [x] CirclesGridMakerでCustomFormを読み込む処理
* [x] HomeActionでCustomFormを読み込む処理
* [x] 企画参加登録画面では、URLにparticipation_typeのIDを含めるようにする
* [x] Circles/ConfirmActionでCustomFormを読み込む処理
* [x] Circles/CreateActionとEditActionとShowActionとStoreActionとUpdateActionとSubmitActionでCustomFormを読み込む処理
* [x] ↑のStaff版
* [x] Circles/Selector/ShowActionでCustomFormを読み込む処理
* [x] Users/InviteActionとUsers/StoreActionでCustomFormを読み込む処理
* [x] Staff/Circles/CustomForm内のAction
* [x] CircleRequest、CustomFormRequestは、URLに含まれるparticipation_typeのIDから適切なバリデーションを行う必要がある
* [x] SubmitedMailable
* [x] Circle/CreatePolicy UpdatePolicy
* [x] CirclesService
* [x] CustomFormFactory
* [x] フォームエディター用には、custom_formとしてフォーム情報を返すようにする
* [x] テスト

---

* [ ] 発行されるSQLの見直し
* [x] 参加種別を削除したら、それに付属している企画参加登録フォームも削除する
* [x] 企画参加登録フォームの回答一覧・設定変更は、申請管理画面側ではできないようにする
* [x] 企画担当者の上限人数を超過している場合は参加登録できない
* [x] FIXMEの修正

**Comment by SofPyon** [comment]
関連: #899
